export const ADD_ARTPIECE_REQUEST = 'ADD_ARTPIECE_REQUEST';
export const ADD_ARTPIECE_SUCCESS = ' ADD_ARTPIECE_SUCCESS';
export const ADD_ARTPIECE_FAIL = 'ADD_ARTPIECE_FAIL';

export const GET_ARTPIECES_REQUEST = 'GET_ARTPIECES_REQUEST';
export const GET_ARTPIECES_SUCCESS = ' GET_ARTPIECES_SUCCESS';
export const GET_ARTPIECES_FAIL = 'GET_ARTPIECES_FAIL';
